### ISSUE TITLE
Application fails when trying to use Play libraries [TestCase provided]

### ISSUE THREAD

**Issue by eximius313** [playframework/play-spring-loader#14]
I wanted to use this library: https://github.com/joscha/play-easymail so I included `"com.feth" %% "play-easymail" % "0.9.5-SNAPSHOT"` into my `build.sbt`
When I run the application I get:
```
play.api.PlayException: Unknown module type[Module [play.api.libs.mailer.SMTPConfigurationModule@37206d] is not a Play module]
        at com.lightbend.play.spring.SpringableModule$.springable(SpringInjector.scala:106)
        at com.lightbend.play.spring.SpringableModule$.$anonfun$loadModules$1(SpringInjector.scala:95)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at com.lightbend.play.spring.SpringableModule$.loadModules(SpringInjector.scala:95)
        at com.lightbend.play.spring.SpringApplicationBuilder$.$anonfun$$lessinit$greater$default$8$1(SpringApplicationBuilder.scala:34)
        at com.lightbend.play.spring.SpringApplicationBuilder.prepareConfig(SpringApplicationBuilder.scala:67)
        at com.lightbend.play.spring.SpringApplicationBuilder.injector(SpringApplicationBuilder.scala:148)
        at com.lightbend.play.spring.SpringApplicationBuilder.build(SpringApplicationBuilder.scala:144)
        at com.lightbend.play.spring.SpringApplicationLoader.load(SpringApplicationLoader.scala:36)
        at play.core.server.DevServerStart$$anon$1.$anonfun$reload$3(DevServerStart.scala:174)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:171)
        at play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:124)
        at play.core.server.AkkaHttpServer.modelConversion(AkkaHttpServer.scala:183)
        at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:189)
        at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:106)
        at akka.stream.impl.fusing.MapAsync$$anon$24.onPush(Ops.scala:1191)
        at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:512)
        at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:475)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:371)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:584)
        at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:468)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:559)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:741)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:756)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:666)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
        at akka.actor.ActorCell.invoke(ActorCell.scala:496)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

**Comment by eximius313** [comment]
Here is the test case: [PlaySpring-easyMailer.zip](https://github.com/playframework/play-spring-loader/files/1671155/PlaySpring-easyMailer.zip)

just run `sbt run` and try to access: `http://localhost:9000/`
