### ISSUE TITLE
Spring 5

### ISSUE THREAD

**Issue by gmethvin** [playframework/play-spring-loader#3]
We should make sure this works with Spring 5 and make the necessary updates.

**Comment by eximius313** [comment]
I'd be happy to test it ;)

**Comment by gmethvin** [comment]
Sure, thanks! I'm not familiar with what changed between 4 and 5. If we need changes we can create a new branch so we can support both versions.

**Comment by eximius313** [comment]
[This article](https://dzone.com/articles/whats-new-in-spring-framework-5) describes it well and [here is the migration guide](https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-5.x) which doesn't look scary at all ;)
If you provide version that I can test I can do it during this weekend

**Comment by gmethvin** [comment]
It's possible the existing version still works, as long as they didn't change any of the core classes that this library uses (this only depends on the `spring-context` library).

> This article describes it well and here is the migration guide which doesn't look scary at all ;)
If you provide version that I can test I can do it during this weekend

I would test with the current version of this library first. If you run into binary compatibility issues, try compiling the library against Spring 5 (you can `sbt publishLocal` and depend on the `0.0.2-SNAPSHOT` version in your Play project to test it).

**Comment by eximius313** [comment]
Do you know why I can't download "Interplay"?
```
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.play#interplay;1.3.12: not found
[error]         at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:331)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:205)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:229)
[error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:190)
[error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]         at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:185)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:182)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:228)
[error]         at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:190)
[error]         at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:38)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:91)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:104)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:104)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:87)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:118)
[error]         at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2353)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:64)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:266)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error]         at java.util.concurrent.FutureTask.run(Unknown Source)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[error]         at java.util.concurrent.FutureTask.run(Unknown Source)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[error]         at java.lang.Thread.run(Unknown Source)
[error] (*:update) sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.play#interplay;1.3.12: not found
```

**Comment by eximius313** [comment]
Compilation of ```play-spring-loader``` with ```Spring 5.0.1``` was complaining just about 2 things:
1. NoSuchBeanDefinitionException constructor: [previously](https://docs.spring.io/autorepo/docs/spring/4.1.0.RELEASE/javadoc-api/org/springframework/beans/factory/NoSuchBeanDefinitionException.html#NoSuchBeanDefinitionException-java.lang.Class-java.lang.String-java.lang.String-) there were 3 arguments and [now](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/beans/factory/NoSuchBeanDefinitionException.html#NoSuchBeanDefinitionException-java.lang.Class-java.lang.String-) there are 2
2. And it also had some problem with ```def isSingleton = false``` saying:
```
[error]  method isSingleton needs `override' modifier
[error]   def isSingleton = false
```
but I have no idea what is it for. When I commented that out my application run without any problems
